- hosts: localhost
  tasks: 
      - docker_container:
              name: "{{ dname}}"
              image: "{{ imagename}}"
              state: started
              privileged: True
              tty: True
              interactive: True
            
