- hosts: localhost
  tasks: 
      - docker_container:
              name: "{{ dname}}"
              image: "{{ imagename}}"
              state: started
              privileged: True
              tty: True
              interactive: True
              detach: True
              env: DISPLAY=$DISPLAY 
              ipc_mode: host
              tmpfs: /tmp/.X11-unix
