- hosts: localhost
  tasks: 
      - debug:
            msg: "{{dname}}"
      - docker_image:
              name: today
              tag: v2
              load_path: /var/www/cgi-bin/docker/centos-latest.tar
              state: present
      - docker_container:
              name: mohitt4
              image: centos
              state: started
              privileged: True
              tty: True
              interactive: True
            
